# Generated by Django 4.2 on 2025-01-17 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_message_creator"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sending",
            options={
                "permissions": [
                    ("can_edit_status", "Может активировать/деактивировать рассылку")
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
