# Generated by Django 4.2 on 2025-01-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_client_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Почта"),
        ),
    ]
